import { expect, test, vi } from 'vitest';
import { flattenSidebar, getSidebar } from '../../utils/navigation';

vi.mock('astro:content', async () =>
	(await import('../test-utils')).mockedAstroContent({
		docs: [
			['guides/z-last.md', { title: 'Z Last', sidebar: { order: 3 } }],
			['guides/a-first.md', { title: 'A First', sidebar: { order: 1 } }],
			['guides/m-middle.md', { title: 'M Middle', sidebar: { order: 2 } }],
		],
	})
);

test('autogenerated sidebar with asc sort orders in ascending order', () => {
	const sidebar = getSidebar('/guides/', undefined);
	const flattened = flattenSidebar(sidebar);

	expect(flattened.map((e) => e.label)).toMatchInlineSnapshot(`
		[
		  "A First",
		  "M Middle",
		  "Z Last",
		]
	`);
});